application: mola-web
version: demo
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /history(/.*)?
  script: maintenance.app
  login: required

- url: /.*
  script: main.app